feat: Implement Export Recorded Data endpoint
edgexfoundry/app-record-replay pull request #42
Opened 2023-07-13 18:30 UTC by marcpfuller

closes #7

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/app-record-replay/blob/main/.github/CONTRIBUTING.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
Run non-secure EdgeX stack
Run `make build`
Run app service with `-cp -d`
Use postman collecting to test GET to `localhost:59712/api/v3/data`

## New Dependency Instructions (If applicable)

2023-07-13 22:54 UTC, jim-wang-intel reviewed
LGTM, upon Lenny's apporval

2023-07-17 16:52 UTC, marcpfuller commented on internal/controller/controller_test.go
> +			Name:             "Valid - no events",
I was wondering about that, I agree. I think we should return `no content`.

2023-07-19 00:51 UTC, lenny-intel requested changes

2023-07-19 00:51 UTC, lenny-intel commented on internal/controller/controller.go
> +	compression := request.URL.Query().Get("Content-Encoding")
I was thinking the query parameter would be `compression`
i.e.
```
/export?compression=GZIP
```
Why did you pick `Content-Encoding` for the query parameter name?
I think the response should sent `Content-Encoding` in the header like you have done. :-)

2023-07-19 00:51 UTC, lenny-intel commented on internal/controller/controller.go
> +		writer.WriteHeader(http.StatusOK)
I think we should be setting `"Content-Type", "application/json"` on all our JSON responses.

2023-07-19 00:51 UTC, lenny-intel commented on internal/controller/controller.go
> +			_, _ = writer.Write([]byte(fmt.Sprintf("%s %s: %s", failedDataCompression, gzipCompression, err)))
```suggestion
			_, _ = writer.Write([]byte(fmt.Sprintf("%s %s: %s", failedDataCompression, zlibCompression, err)))
```

2023-07-19 00:51 UTC, lenny-intel commented on internal/controller/controller.go
> +		writer.WriteHeader(http.StatusOK)
Move this down like it is in gzip case? or does that one need to be moved up?

2023-07-20 00:20 UTC, lenny-intel approved these changes
LGTM

2023-07-20 00:21 UTC, merged