Import data
edgexfoundry/app-record-replay pull request #56
Opened 2023-08-04 22:10 UTC by marcpfuller

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/app-record-replay/blob/main/.github/CONTRIBUTING.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2023-08-04 22:13 UTC, marcpfuller commented
Recheck

2023-08-09 18:42 UTC, jim-wang-intel reviewed
some question about logic when errors happen

2023-08-09 18:42 UTC, jim-wang-intel commented on internal/controller/controller.go
> +			_, _ = writer.Write([]byte(fmt.Sprintf("%s: %v", failedRequestJSON, err)))
if there is an error, should we return here right away?

2023-08-09 18:42 UTC, jim-wang-intel commented on internal/controller/controller.go
> +				_, _ = writer.Write([]byte(fmt.Sprintf("%s: %s", failedToUncompressData, err)))
ditto

2023-08-09 18:42 UTC, jim-wang-intel commented on internal/controller/controller.go
> +				_, _ = writer.Write([]byte(fmt.Sprintf("%s: %s", failedToUncompressData, err)))
ditto

2023-08-09 18:42 UTC, jim-wang-intel commented on internal/controller/controller.go
> +			_, _ = writer.Write([]byte(fmt.Sprintf("%s: %v", failedRequestJSON, err)))
ditto

2023-08-09 19:08 UTC, jim-wang-intel commented on internal/application/manager.go
> +func (m *dataManager) ImportRecordedData(data *dtos.RecordedData, overwrite bool) error {
also in the golang docs could you add what `overwrite` bool is for?

2023-08-09 19:09 UTC, jim-wang-intel commented on internal/interfaces/manager.go
> +	ImportRecordedData(data *dtos.RecordedData, overwrite bool) error
same here, add what `overwirte` bool is for

2023-08-09 21:11 UTC, jim-wang-intel submitted a review, later dismissed
LGTM,  upon @lenny-intel 's review

2023-08-14 15:36 UTC, lenny-intel requested changes

2023-08-14 15:36 UTC, lenny-intel commented on internal/controller/controller.go
> +	noDataFound         = "no recorded data found"
Move these up with the other err messages

2023-08-14 15:36 UTC, lenny-intel commented on internal/controller/controller.go
>  	}
`ExportRecordedData` should return an error when there isn't any recorded data, so this check should be removed.

2023-08-14 15:36 UTC, lenny-intel commented on internal/controller/controller.go
> +	compression := request.URL.Query().Get("compression")
Per the ADR you should be determining this via the `Content-Encoding` header.
https://docs.edgexfoundry.org/3.0/design/adr/application/0025-Record-and-Replay/#post_2

2023-08-14 15:36 UTC, lenny-intel commented on internal/controller/controller.go
> +	overWriteProfilesDevices, err = strconv.ParseBool(request.URL.Query().Get("overwrite"))
`overwrite` is optional and defaults to `true`. What happens here when to provided.
https://docs.edgexfoundry.org/3.0/design/adr/application/0025-Record-and-Replay/#post_2

2023-08-14 15:36 UTC, lenny-intel commented on internal/controller/controller.go
> +		err = json.NewDecoder(request.Body).Decode(&importedRecordedData)
This block is repeated. Restructure code so that it isn't repeated.

2023-08-14 15:36 UTC, lenny-intel commented on internal/controller/controller.go
> +	}
I think we should be more detailed here. I.e. first check for Events not Empty  (need at least 1) , then Devices not empty (need at least 1) and then Profiles not Empty (need at least 1) . This give better feedback to user. Also should return `BadRequest` in this situation

2023-08-14 15:36 UTC, lenny-intel commented on internal/controller/controller_test.go
> +	}
Need a profile also

2023-08-14 15:36 UTC, lenny-intel commented on internal/controller/controller_test.go
> +			query.Add("compression", test.CompressionParam)
Need to set `Content-Encoding` instead using standard HTTP header values.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

2023-08-15 19:47 UTC, marcpfuller commented on internal/controller/controller_test.go
> +				mockDataManager.On("ImportRecordedData", mock.Anything, mock.Anything).Return(test.ExpectedError).Once()
It is needed, the next test (gzip) returns the error from the previous test.

2023-08-15 20:44 UTC, lenny-intel commented on internal/controller/controller_test.go
> +				mockDataManager.On("ImportRecordedData", mock.Anything, mock.Anything).Return(test.ExpectedError).Once()
How does it `returns the error from the previous test`

2023-08-15 23:05 UTC, lenny-intel requested changes

2023-08-15 23:05 UTC, lenny-intel commented on internal/controller/controller.go
> +	compression := request.Header.Get("Content-Encoding")
Move this down to just above the switch where it is used.

2023-08-15 23:05 UTC, lenny-intel commented on internal/controller/controller.go
> +		_, _ = writer.Write([]byte("compression format not supported"))
```suggestion
		_, _ = writer.Write([]byte(fmt.Sprintf("compression format '%s' not supported", compression))
```

2023-08-15 23:22 UTC, jim-wang-intel submitted a review, later dismissed
other than Lenny's comments, LGTM

2023-08-15 23:54 UTC, lenny-intel commented
@mark, please expand to `full testing` description above to include a uncompressed JSON file.

2023-08-17 00:34 UTC, marcpfuller commented
> @marcpfuller , please expand to `full testing` description above to include a uncompressed JSON file.

@lenny-intel I added a uncompressed json file

2023-08-17 01:04 UTC, lenny-intel commented
> > @marcpfuller , please expand to `full testing` description above to include a uncompressed JSON file.
> 
> @lenny-intel I added a uncompressed json file

@marcpfuller , I see the new unit test, which  is great, but I was referring to the full test instruction above in the PR description. You only have the two compression, not un-compressed JSON file

2023-08-21 21:34 UTC, lenny-intel approved these changes
LGTM

2023-08-21 21:34 UTC, merged